### ISSUE TITLE
Allow cleanup with import and without archive

### ISSUE THREAD

**Issue by giga** [fxstein/GoProX#16]
Contrary to the readme, cleanup is only allowed when archiving.

Archiving and importing everything is taking a lot of space.

It would be great if cleanup was allowed for import only as well. Maybe with an additional option if import is considered dangerous and could damage file?

**Comment by fxstein** [comment]
You are right. Somehow I wrote the readme how it should work. Will fix asap. 
I archive all my cards as I needed the ability to re-import after changes. But it does take a lot of space. 
Thank you!
