### ISSUE TITLE
Check for errors when importing files

### ISSUE THREAD

**Issue by giga** [fxstein/GoProX#18]
Exit status of exiftool in _import_media function is not checked. This is dangerous especially since cleanup can now be used with import.

**Comment by fxstein** [comment]
Now I remember why I originally did not allow clean with import only. Had some issues with the exit status of exiftool. Need to investigate and do some testing.

**Comment by fxstein** [comment]
So here is the issue:

I need the ability to re-import and re-process files, sometimes all, sometimes sparse - e.g. just the missing files. When an output file already exists, exiftool throws an error and moves to the next files. These are acceptable errors as the default behavior of goprox is based on skipping existing files. However it means the error status of exiftool is no longer 0.

Other errors obviously need to get caught. Need to see if I can tell exiftool and existing target files errors are to be ignore while others are not.

**Comment by giga** [comment]
I think it would still be dangerous to clean files if some existing files were skipped.

Imagine an import is stopped in the middle for whatever reason (power outage, disconnected drive…), one of the file may be existing but incomplete. If the user does not pay attention and blindly runs the command again, a file will be lost.

It would not seem a problem to me if cleanup were allowed only when exiftool return no error. In the case were exiftool fails, it would be the responsibility of the user to solve the problem (use archive and cleanup, manually cleanup, or remove existing files and run the command again).

What do you think?

**Comment by fxstein** [comment]
That is indeed a potentially simple solution. Also still looking at some exiftool options. Will get back asap.

**Comment by fxstein** [comment]
FYI This is why I personally always make archives that I store separately, even at the cost of a lot of extra storage, because it is the one guarantee I have to be able to re-run from scratch. Especially since developing `goprox` is still missing key features that I would like to apply to parts of my historic library.

But this issue needs to be addressed no matter what.

**Comment by fxstein** [comment]
@giga Pushed the initial error handling logic as discussed. Can you test before I cut this into a new release? Thanks!

**Comment by giga** [comment]
Hello,

Many thanks for the reactivity. I have this error with latest version: _clean_media:[:8: ']' expected

**Comment by fxstein** [comment]
Can you share more details?

Would be great if you could run your command with --debug and copy the output here.

Thanks!
